### ISSUE TITLE
Import statement

### ISSUE THREAD

**Issue by GaryHilares** [rajlang/Syntax#2]
**Is your feature request related to a problem? Please describe.**
Many languages like Python, Java and JavaScript have different ways to import other files or functions.

**Describe the solution you'd like**
A syntax to import functions or other files.

**Describe alternatives you've considered**
Probably we could mimic the Python import syntax and parse it to the syntax of the other languages.

**Comment by Rajaniraiyn** [comment]
See the discussion #4
